### ISSUE TITLE
 mode: TextScrollMode.endless is not working

### ISSUE THREAD

**Issue by mhdshuhaib1704** [yurii-khi/text_scroll#12]
_AssertionError ('package:flutter/src/widgets/scroll_controller.dart': Failed assertion: line 152 pos 12: '_positions.isNotEmpty': ScrollController not attached to any scroll views.)

**Comment by yurii-khi** [comment]
Hey @mhdshuhaib1704 !
Thanks for the report. Unfortunately I was not able to reproduce it on my side.
Could you please provide more details, like `flutter doctor` output, target platform, or even code example?
