### ISSUE TITLE
Text align does not work

### ISSUE THREAD

**Issue by Swepilot** [yurii-khi/text_scroll#32]
When trying to align a text too short to scroll, setting the textAlign property to e.g. TextAlign.right, the text is still left aligned. 
<img width="365" alt="image" src="https://user-images.githubusercontent.com/19726458/224534035-c92046c8-ce56-4687-a60d-e9fb4450f8af.png">

```dart
Container(
              color: Colors.black,
                height: 30,
                width: MediaQuery.of(context).size.width,
                child: Row(
                  children: [
                    Expanded(
                      child: TextScroll(
                        "Short text",
                        style:
                            const TextStyle(color: Colors.white, fontSize: 20),
                        textAlign: TextAlign.right,
                      ),
                    ),
                  ],
                ),
              );
```
If I change the TextScroll in the code above to a normal Text widget the text is right aligned.
<img width="365" alt="image" src="https://user-images.githubusercontent.com/19726458/224534067-7ebee1ce-819a-430a-a76c-c0e1bf859a21.png">

**Comment by yurii-khi** [comment]
Thanks for feedback @Swepilot, it should be resolved in #29.
